### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by OhJackHu** [chou141253/FGVC-PIM#11]
I'm at swinvit12.py write self extractor = load_ model_ weights (self. extractor, ". / Models / swing_large_patch4_windows12_384_22k. pth") runs with the following error:

Traceback (most recent call last):
  File "train.py", line 396, in <module>
    train_loader, test_loader, model, optimizer, schedule = set_environment(args)
  File "train.py", line 94, in set_environment
    model = SwinVit12(
  File "/home/pengtl/jackhu/FGVC-PIM-master/models/SwinVit12.py", line 203, in __init__
    self.extractor = load_model_weights(self.extractor, "/home/pengtl/jackhu/FGVC-PIM-master/swin_large_patch4_window12_384_22k.pth")
  File "/home/pengtl/jackhu/FGVC-PIM-master/models/SwinVit12.py", line 16, in load_model_weights
    if key in state['state_dict']:
KeyError: 'state_dict'

**Comment by OhJackHu** [comment]
If I use the following code, can I avoid downloading pre training weights？

self.extractor = timm.create_model('swin_large_patch4_window12_384_in22k', pretrained=False)
self.extractor = load_model_weights(self.extractor, './swin_large_patch4_window12_384_in22k.pth')

**Comment by chou141253** [comment]
Sure! But we use timm model, please check the pre-trained model is fitting timm provided.

**Comment by OhJackHu** [comment]
> Sure! But we use timm model, please check the pre-trained model is fitting timm provided.
I used the following code and used the pre-training weight downloaded by myself, and the following errors occurred:
self.extractor = timm.create_model('swin_large_patch4_window12_384_in22k', pretrained=False)
self.extractor = load_model_weights(self.extractor, './swin_large_patch4_window12_384_in22k.pth')
![QQ截图20220424203606](https://user-images.githubusercontent.com/76413688/164978118-f9d0875d-642c-4efd-a6b1-6365ab269692.jpg)

**Comment by zzr9zzr** [comment]
> I used the pre-training weight downloaded by myself, and the following errors occurred:
> 
> ![QQ截图20220424203606](https://user-images.githubusercontent.com/76413688/164978118-f9d0875d-642c-4efd-a6b1-6365ab269692.jpg)

you should change the 'state_dict' to 'model'.
